config/routes.rb
ArduinoSimulator::Application.routes.draw do
  get "sensors/index", as: "sensors"
  post "sensors/index" => "sensors#forwardSensorValues"
  get "sensors/serial" => "sensors#getLastReadLine"

  get "sensors/addArduino" => "sensors#addArduino"
  get "welcome/index"

  root 'welcome#index'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/sensors_controller.rb
require 'serialport'
require 'arduino'


class SensorsController < ApplicationController
  protect_from_forgery with: :null_session, if: Proc.new { |c| c.request.format == 'application/json' }
  @@sockets = Hash.new
  @@socats = Hash.new

  before_filter :init_socket
  def init_socket
  end

  def index
  end

  # Forwards the received values of one instantiated Arduino sketch as JSON on
  # the selected serial port. Ideally, the REST-server listens on this serial
  # port and makes so these values accessible for clients over a REST-interface.
  def forwardSensorValues
    logger.debug  "This is my params: "+params["data"]["temperature"].to_s
    logger.debug "This is my params: "+params["data"]["temperature"].to_s
    rp = params["data"]["temperature"].to_i + 1
    respond_to do |format|
      format.json {render :json => { :value => rp }.to_json}
    end
    if !@@sockets[params["serialPort"]]
      create_socket(params["serialPort"])
    end
    @@sockets[params["serialPort"]].write(params["data"].to_json)
  end

  # For a given serial port, returns the last new received line.
  def getLastReadLine
    sp = params["sp"].to_s
    begin
      nextline = @@sockets[sp].next
    rescue NoMethodError
      nextline = "{}"
    end
    logger.debug  nextline
    json_line = JSON.parse(nextline, symbolize_names: true)

    respond_to do |format|
      format.json {render :json => {:serialPort => sp, :data => json_line}.to_json}
    end
  end

  # Method used to send back the desired Arduino sketch so it can be added to the list of instantiated Arduino
  # sketches in the interface. This is a function which is called from javascript over an
  # Ajax action. The result is just a bunch of HTML rendered as string and packaged into a JSON array.
  def addArduino
    type = params["type"].to_s
    logger.debug  "Will create "+type
    arduinoNumber = rand(9999999)
    arduinoNumber2 = rand(9999999)
    arduinoNumber3 = rand(9999999)
    case type
      when 'dht11'
        arduinoPart = 'sensors/dht11'
      when 'light'
        arduinoPart = 'sensors/light'
      when 'led'
        arduinoPart = 'sensors/led'
      when 'switch'
        arduinoPart = 'sensors/switch'
      when 'motor'
        arduinoPart = 'sensors/motor'
      when 'lightbulb'
        arduinoPart = 'sensors/lightbulb'
      when 'smartdoor'
        arduinoPart = 'sensors/smartdoor'
      else
        arduinoPart = 'sensors/dht11'
    end

    respond_to do |format|
      format.json {render :json => { :value => render_to_string(:partial => arduinoPart, :formats => [:html], :layout => false, :locals => {:arduinoNumber => arduinoNumber, :arduinoNumber2 => arduinoNumber2, :arduinoNumber3 => arduinoNumber3}) }.to_json}
    end
  end

  private

  # Utility Method to create an instance of socat with the chosen port on one side and the chosen port+1 on
  # the output side.
  # Params:
  # +port+:: the port name on the one side of the socat channel
  # Example:
  #  create_socket('COM1') => creates a socat between COM1 and COM2
  def create_socket(port) #:doc:
    splitted = port.split(//)
    splitted[splitted.size - 1] = (splitted[splitted.size - 1].to_i + 1).to_s
    port2 = splitted.join()

    @@socats[port] = IO.popen('socat -d -d pty,raw,echo=0,link='+AS_CONFIG['homedir']+port+' pty,raw,echo=0,link='+AS_CONFIG['homedir']+port2)
    sleep(2)
    @@sockets[params["serialPort"]] = Arduino::Arduino.new(AS_CONFIG['homedir']+port)
    @@sockets[params["serialPort"]].read
    return 0
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sensors_helper.rb
module SensorsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_footer.html.erb
<footer style="background-color: #f0f0f0;">
  <div style="text-align: right;">
    Andreas Ruppen
  </div>
</footer>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
    <% if msg.is_a?(String) %>
        <div data-alert class="alert-box
        <%= name.to_s == 'notice' ? 'success' : 'alert' %>">
          <%= content_tag :div, msg %>
          <a href="#" class="close">&times;</a>
        </div>
    <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<header style="margin-bottom: 20px;">
  <nav class="top-bar" data-topbar>
    <!-- Area reserved for title -->
    <ul class="title-area">
      <li class="name">
        <h1><a href="<%= root_path %>"><i class="fi-anchor"></i> Arduino Simluator</a></h1>
      </li>
      <li class="toggle-topbar menu-icon">
        <a>Menu</a>
      </li>
    </ul>
    <section class="top-bar-section">
      <ul class="left">
        <li><%=link_to "Sensors", sensors_path %></li>
      </ul>

    </section>

  </nav>

  <!-- Error Messages -->
  <%= render 'layouts/messages' %>

</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Arduino Simulator" %></title>


    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    "application" %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <div id="body_content" class="row">
      <div class="column large-10 large-centered">
        <%= yield %>
      </div>
    </div>
    <%= javascript_include_tag "application" %>
  </body>
  <%= render 'layouts/footer' %>
</html>

app/views/sensors/_dht11.html.erb
<div class="row arduino<%=arduinoNumber%>">
  <div class="panel callout radius">
    <div class="fi-eject right" onclick="removeArduino('arduino<%=arduinoNumber%>')"></div>
    <div class="row">
      <span class="label">DHT11 Sensor</span>
    </div>
    <div class="row">
      <select id="serialPortSelector" class="com1 columns large-4 right" onchange="updateComPort('arduino<%=arduinoNumber%>', this)">
        <option value="null">Select Port</option>
        <option value="COM1">COM1</option>
        <option value="COM3">COM3</option>
        <option value="COM5">COM5</option>
        <option value="COM7">COM7</option>
        <option value="COM9">COM9</option>
      </select>
    </div>
    <div class="row">
      <span class="columns large-3">Thermistor </span>
      <input id="temperature" type="range"  min="0" max="100" onchange="xwotcallback('arduino<%=arduinoNumber%>')" class="xwot sensor columns large-8"/>
      <span id="temperaturetext" class="columns large-1">0</span>
    </div>
    <div class="row">
      <span class="columns large-3">Humidity </span>
      <input id="humidity" type="range"  min="0" max="100" onchange="xwotcallback('arduino<%=arduinoNumber%>')" class="xwot sensor columns large-8"/>
      <span id="humiditytext" class="columns large-1">0</span>
    </div>
  </div>
</div>

app/views/sensors/_led.html.erb
<div class="row arduino<%=arduinoNumber%>">
  <div class="panel callout radius">
    <div class="fi-eject right" onclick="removeArduino('arduino<%=arduinoNumber%>')"></div>
    <div class="row">
      <span class="label">LED</span>
    </div>
    <div class="row">
      <select id="serialPortSelector" class="com1 columns large-4 right" onchange="updateComPort('arduino<%=arduinoNumber%>', this)">
        <option value="null">Select Port</option>
        <option value="COM1">COM1</option>
        <option value="COM3">COM3</option>
        <option value="COM5">COM5</option>
        <option value="COM7">COM7</option>
        <option value="COM9">COM9</option>
      </select>
    </div>
    <div class="row">
      <span class="columns large-3">LED </span>
      <div class="columns left switch round large-4">
        <input id="led<%=arduinoNumber%>" type="checkbox" onchange="xwotcallback('arduino<%=arduinoNumber%>')" class="xwot actuator">
        <label for="led<%=arduinoNumber%>"></label>
      </div>
    </div>
  </div>
</div>

app/views/sensors/_light.html.erb
<div class="row arduino<%=arduinoNumber%>">
  <div class="panel callout radius">
    <div class="fi-eject right" onclick="removeArduino('arduino<%=arduinoNumber%>')"></div>
    <div class="row">
      <span class="label">Luminosity Sensor</span>
    </div>
    <div class="row">
      <select id="serialPortSelector" class="com1 columns large-4 right" onchange="updateComPort('arduino<%=arduinoNumber%>', this)">
        <option value="null">Select Port</option>
        <option value="COM1">COM1</option>
        <option value="COM3">COM3</option>
        <option value="COM5">COM5</option>
        <option value="COM7">COM7</option>
        <option value="COM9">COM9</option>
      </select>
    </div>
    <div class="row">
      <span class="columns large-3">Luminosity </span>
      <input id="luminosity" type="range"  min="0" max="100" onchange="xwotcallback('arduino<%=arduinoNumber%>')" class="xwot sensor columns large-8"/>
      <span id="luminositytext" class="columns large-1">0</span>
    </div>
  </div>
</div>

app/views/sensors/_lightbulb.html.erb
<div class="row arduino<%=arduinoNumber%>">
  <div class="panel callout radius">
    <div class="fi-eject right" onclick="removeArduino('arduino<%=arduinoNumber%>')"></div>
    <div class="row">
      <span class="label">Smart Light Bulb</span>
    </div>
    <div class="row">
      <select id="serialPortSelector" class="com1 columns large-4 right" onchange="updateComPort('arduino<%=arduinoNumber%>', this)">
        <option value="null">Select Port</option>
        <option value="COM1">COM1</option>
        <option value="COM3">COM3</option>
        <option value="COM5">COM5</option>
        <option value="COM7">COM7</option>
        <option value="COM9">COM9</option>
      </select>
    </div>
    <div class="row">
      <span class="columns large-3">Light Sensor </span>
      <input id="lightsensor" type="range"  min="0" max="100" onchange="xwotcallback('arduino<%=arduinoNumber%>')" class="xwot sensor columns large-8"/>
      <span id="lightsensortext" class="columns large-1">0</span>
    </div>
    <div class="row">
      <span class="columns large-3">Light Switch </span>
      <div class="columns left switch round large-4">
        <input id="lightswitch<%=arduinoNumber%>" type="checkbox" onchange="xwotcallback('arduino<%=arduinoNumber%>')" class="xwot actuator">
        <label for="lightswitch<%=arduinoNumber%>"></label>
      </div>
    </div>
  </div>
</div>

app/views/sensors/_motor.html.erb
<div class="row arduino<%=arduinoNumber%>">
  <div class="panel callout radius">
    <div class="fi-eject right" onclick="removeArduino('arduino<%=arduinoNumber%>')"></div>
    <div class="row">
      <span class="label">Motor</span>
    </div>
    <div class="row">
      <select id="serialPortSelector" class="com1 columns large-4 right" onchange="updateComPort('arduino<%=arduinoNumber%>', this)">
        <option value="null">Select Port</option>
        <option value="COM1">COM1</option>
        <option value="COM3">COM3</option>
        <option value="COM5">COM5</option>
        <option value="COM7">COM7</option>
        <option value="COM9">COM9</option>
      </select>
    </div>
    <div class="row">
      <span class="columns large-3">Motor </span>
      <div class="columns left switch round large-4">
        <input id="motor<%=arduinoNumber%>" type="checkbox" onchange="xwotcallback('arduino<%=arduinoNumber%>')" class="xwot actuator">
        <label for="motor<%=arduinoNumber%>"></label>
      </div>
    </div>
  </div>
</div>

app/views/sensors/_smartdoor.erb
<div class="row arduino<%= arduinoNumber %>">
  <div class="panel callout radius">
    <div class="fi-eject right" onclick="removeArduino('arduino<%=arduinoNumber%>')"></div>
    <div class="row">
      <span class="label">Smart Door</span>
    </div>
    <div class="row">
      <div class="arduino<%= arduinoNumber2 %>">
        <div class="panel callout radius">
          <div class="row">
            <span class="label">Locked Mechanism</span>
          </div>
          <div class="row">
            <select id="serialPortSelector" class="com1 columns large-4 right" onchange="updateComPort('arduino<%=arduinoNumber2%>', this)">
              <option value="null">Select Port</option>
              <option value="COM1">COM1</option>
              <option value="COM3">COM3</option>
              <option value="COM5">COM5</option>
              <option value="COM7">COM7</option>
              <option value="COM9">COM9</option>
            </select>
          </div>
          <div class="row">
            <span class="columns large-3">Locked / Unlocked </span>

            <div class="columns left switch round large-4">
              <input id="locked<%= arduinoNumber2 %>" type="checkbox" onchange="xwotcallback('arduino<%=arduinoNumber2%>')" class="xwot actuator">
              <label for="locked<%= arduinoNumber2 %>"></label>
            </div>
          </div>
        </div>
      </div>
      <div class="arduino<%= arduinoNumber3 %>">
        <div class="panel callout radius">
          <div class="row">
            <span class="label">Opening Mechanism</span>
          </div>
          <div class="row">
            <select id="serialPortSelector" class="com1 columns large-4 right" onchange="updateComPort('arduino<%=arduinoNumber3%>', this)">
              <option value="null">Select Port</option>
              <option value="COM1">COM1</option>
              <option value="COM3">COM3</option>
              <option value="COM5">COM5</option>
              <option value="COM7">COM7</option>
              <option value="COM9">COM9</option>
            </select>
          </div>
          <div class="row">
            <span class="columns large-3">Open / Close </span>
            <input id="open" type="range" min="0" max="100" onchange="xwotcallback('arduino<%=arduinoNumber3%>')" class="xwot sensor columns large-8"/>
            <span id="humiditytext" class="columns large-1">0</span>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/sensors/_switch.html.erb
<div class="row arduino<%=arduinoNumber%>">
  <div class="panel callout radius">
    <div class="fi-eject right" onclick="removeArduino('arduino<%=arduinoNumber%>')"></div>
    <div class="row">
      <span class="label">Switch</span>
    </div>
    <div class="row">
      <select id="serialPortSelector" class="com1 columns large-4 right" onchange="updateComPort('arduino<%=arduinoNumber%>', this)">
        <option value="null">Select Port</option>
        <option value="COM1">COM1</option>
        <option value="COM3">COM3</option>
        <option value="COM5">COM5</option>
        <option value="COM7">COM7</option>
        <option value="COM9">COM9</option>
      </select>
    </div>
    <div class="row">
      <span class="columns large-3">Stomp Box </span>
      <div class="columns left switch round large-4">
        <input id="switch<%=arduinoNumber%>" type="checkbox" onchange="xwotcallback('arduino<%=arduinoNumber%>')" class="xwot actuator">
        <label for="switch<%=arduinoNumber%>"></label>
      </div>
    </div>
  </div>
</div>

app/views/sensors/index.html.erb
<div class="row">
  <div class="columns large-3 panel">
    <div class="panel callout radius">
      <div class="row">
        <span class="label">Sensors</span>
      </div>
      <div id="log1" onclick="instantiateArduino('dht11')"><a href="#">DHT11</a></div>
      <div id="log2" onclick="instantiateArduino('light')"><a href="#">Light Sensor</a></div>
    </div>

    <div class="panel callout radius">
      <div class="row">
        <span class="label">Actuators</span>
      </div>
      <div id="log3" onclick="instantiateArduino('led')"><a href="#">Led</a></div>
      <div id="log4" onclick="instantiateArduino('switch')"><a href="#">Switch Button</a></div>
      <div id="log5" onclick="instantiateArduino('motor')"><a href="#">Motor</a></div>
    </div>
    <div class="panel callout radius">
      <div class="row">
        <span class="label">Scenarios</span>
      </div>
      <div id="log6" onclick="instantiateArduino('lightbulb')"><a href="#">Smart Light Bulb</a></div>
      <div id="log7" onclick="instantiateArduino('smartdoor')"><a href="#">Smart Door</a></div>
      <div id="log4"></div>
    </div>
  </div>


  <div id="arduinoContainer" class="columns large-7 panel">

    <div class="row arduino1234">
      <div class="panel callout radius">
        <div class="fi-eject right" onclick="removeArduino('arduino1234')"></div>
        <div class="row">
          <span class="label">Meteo Sensor</span>
        </div>
        <div class="row">
          <select id="serialPortSelector" class="com1 columns large-4 right" onchange="updateComPort('arduino1234', this)">
            <option value="null">Select Port</option>
            <option value="COM1">COM1</option>
            <option value="COM3">COM3</option>
            <option value="COM5">COM5</option>
            <option value="COM7">COM7</option>
            <option value="COM9">COM9</option>
          </select>
        </div>
        <div class="row">
          <span class="columns large-3">Thermistor </span>
          <input id="temperature" type="range" min="0" max="100" onchange="xwotcallback('arduino1234')" class="xwot sensor columns large-8"/>
          <span id="temperaturetext" class="columns large-1">0</span>
        </div>
        <div class="row">
          <span class="columns large-3">Humidity </span>
          <input id="humidity" type="range" min="0" max="100" onchange="xwotcallback('arduino1234')" class="xwot sensor columns large-8"/>
          <span id="humiditytext" class="columns large-1">0</span>
        </div>
      </div>
    </div>


    <div class="row arduino4321">
      <div class="panel callout radius">
        <div class="fi-eject right" onclick="removeArduino('arduino4321')"></div>
        <div class="row">
          <span class="label">Meteo Sensor</span>
        </div>
        <div class="row">
          <select id="serialPortSelector" class="com1 columns large-4 right" onchange="updateComPort('arduino4321', this)">
            <option value="null">Select Port</option>
            <option value="COM1">COM1</option>
            <option value="COM3">COM3</option>
            <option value="COM5">COM5</option>
            <option value="COM7">COM7</option>
            <option value="COM9">COM9</option>
          </select>
        </div>
        <div class="row">
          <span class="columns large-3">Light Sensor </span>
          <input id="lightsensor" type="range" min="0" max="100" onchange="xwotcallback('arduino4321')" class="xwot sensor columns large-8"/>
          <span id="lightsensortext" class="columns large-1">0</span>
        </div>
        <div class="row">
          <span class="columns large-3">Light Switch </span>

          <div class="columns left switch round large-4">
            <input id="lightswitch" type="checkbox" onchange="xwotcallback('arduino4321')" class="xwot actuator">
            <label for="lightswitch"></label>
          </div>
        </div>
      </div>
    </div>


  </div>
</div>

app/views/welcome/index.html.erb
<div id="main" class="full-modal columns large-7 panel">

  <div class="row">
    <div class="small-12 medium-6 columns" id="login">
      <h1>Arduino Simulator</h1>
      <div class="small-6 large-centered columns"><%= link_to "Go To Breadboard", sensors_path, :class => "button expand" %> </div>
    </div>
  </div>
</div>